[functions.izzy-create-lead]
enabled = true
verify_jwt = false
import_map = "./functions/izzy-create-lead/deno.json"
entrypoint = "./functions/izzy-create-lead/index.ts"

[functions.izzy-admin-leads]
enabled = true
verify_jwt = false
import_map = "./functions/izzy-admin-leads/deno.json"
entrypoint = "./functions/izzy-admin-leads/index.ts"

[functions.izzy-create-order]
enabled = true
verify_jwt = false
import_map = "./functions/izzy-create-order/deno.json"
entrypoint = "./functions/izzy-create-order/index.ts"

[functions.izzy-compensation]
enabled = true
verify_jwt = false
import_map = "./functions/izzy-compensation/deno.json"
entrypoint = "./functions/izzy-compensation/index.ts"

[functions.izzy-call-center]
enabled = true
verify_jwt = false
import_map = "./functions/izzy-call-center/deno.json"
entrypoint = "./functions/izzy-call-center/index.ts"
