begin;

create table if not exists public.izzy_lead_activities (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.izzy_leads(id) on delete cascade,
  agent_user_id bigint references public.izzy_portal_users(id) on delete set null,
  activity_type text not null,
  activity_source text not null default 'call_center',
  title text,
  body text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint izzy_lead_activities_type_check
    check (
      activity_type in (
        'call_logged',
        'status_changed',
        'note_added',
        'followup_created',
        'followup_completed',
        'followup_rescheduled',
        'quote_requested'
      )
    )
);

create index if not exists izzy_lead_activities_lead_created_idx
  on public.izzy_lead_activities (lead_id, created_at desc);

create index if not exists izzy_lead_activities_agent_created_idx
  on public.izzy_lead_activities (agent_user_id, created_at desc);

alter table public.izzy_lead_activities enable row level security;
alter table public.izzy_lead_activities force row level security;

revoke all privileges on table public.izzy_lead_activities from anon, authenticated;

commit;
