begin;

create table if not exists public.izzy_followups (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.izzy_leads(id) on delete cascade,
  agent_user_id bigint not null references public.izzy_portal_users(id) on delete restrict,
  source_call_id bigint references public.izzy_lead_calls(id) on delete set null,
  status text not null default 'scheduled',
  scheduled_for timestamptz not null,
  completed_at timestamptz,
  subject text,
  notes text,
  outcome text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_followups_status_check
    check (status in ('scheduled', 'completed', 'missed', 'cancelled'))
);

create index if not exists izzy_followups_lead_idx
  on public.izzy_followups (lead_id, scheduled_for desc);

create index if not exists izzy_followups_agent_status_idx
  on public.izzy_followups (agent_user_id, status, scheduled_for);

drop trigger if exists set_izzy_followups_updated_at on public.izzy_followups;
create trigger set_izzy_followups_updated_at
before update on public.izzy_followups
for each row execute function public.set_updated_at();

alter table public.izzy_followups enable row level security;
alter table public.izzy_followups force row level security;

revoke all privileges on table public.izzy_followups from anon, authenticated;

commit;
