begin;

create table if not exists public.izzy_portal_users (
  id bigint generated by default as identity primary key,
  pin_code text not null unique,
  nombre text not null,
  rol text not null check (rol in ('admin', 'agente')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.izzy_quoters (
  id bigint generated by default as identity primary key,
  code text not null unique,
  nombre text not null,
  telefono text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_izzy_portal_users_updated_at on public.izzy_portal_users;
create trigger set_izzy_portal_users_updated_at
before update on public.izzy_portal_users
for each row execute function public.set_updated_at();

drop trigger if exists set_izzy_quoters_updated_at on public.izzy_quoters;
create trigger set_izzy_quoters_updated_at
before update on public.izzy_quoters
for each row execute function public.set_updated_at();

alter table public.izzy_portal_users enable row level security;
alter table public.izzy_portal_users force row level security;
alter table public.izzy_quoters enable row level security;
alter table public.izzy_quoters force row level security;

revoke all privileges on table public.izzy_portal_users from anon, authenticated;
revoke all privileges on table public.izzy_quoters from anon, authenticated;

insert into public.izzy_portal_users (pin_code, nombre, rol, active)
values
  ('CAIM0001', 'MOISES CAICEDO', 'admin', true),
  ('CAID0001', 'DAVID CAICEDO', 'agente', true),
  ('OSPP0001', 'PATRICIA CAICEDO', 'agente', true)
on conflict (pin_code) do update
set
  nombre = excluded.nombre,
  rol = excluded.rol,
  active = excluded.active;

insert into public.izzy_quoters (code, nombre, telefono, active)
values
  ('PCAI', 'PATRICIA CAICEDO', '7862913042', true)
on conflict (code) do update
set
  nombre = excluded.nombre,
  telefono = excluded.telefono,
  active = excluded.active;

commit;
