begin;

create table if not exists public.izzy_lead_calls (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.izzy_leads(id) on delete cascade,
  agent_user_id bigint not null references public.izzy_portal_users(id) on delete restrict,
  direction text not null default 'outbound',
  call_status text not null,
  disposition text not null,
  notes text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer,
  next_action text,
  next_followup_at timestamptz,
  created_at timestamptz not null default now(),
  constraint izzy_lead_calls_direction_check
    check (direction in ('inbound', 'outbound')),
  constraint izzy_lead_calls_call_status_check
    check (
      call_status in (
        'answered',
        'no_answer',
        'voicemail',
        'wrong_number',
        'call_back',
        'interested',
        'not_interested',
        'quote_requested'
      )
    ),
  constraint izzy_lead_calls_disposition_check
    check (
      disposition in (
        'answered',
        'no_answer',
        'voicemail',
        'wrong_number',
        'call_back',
        'interested',
        'not_interested',
        'quote_requested'
      )
    )
);

create index if not exists izzy_lead_calls_lead_started_idx
  on public.izzy_lead_calls (lead_id, started_at desc);

create index if not exists izzy_lead_calls_agent_started_idx
  on public.izzy_lead_calls (agent_user_id, started_at desc);

alter table public.izzy_lead_calls enable row level security;
alter table public.izzy_lead_calls force row level security;

revoke all privileges on table public.izzy_lead_calls from anon, authenticated;

commit;
