begin;

create table if not exists public.izzy_password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.izzy_portal_users(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz
);

create index if not exists izzy_password_reset_tokens_user_idx
  on public.izzy_password_reset_tokens (user_id, created_at desc);

create index if not exists izzy_password_reset_tokens_active_idx
  on public.izzy_password_reset_tokens (expires_at)
  where used_at is null;

alter table public.izzy_password_reset_tokens enable row level security;
alter table public.izzy_password_reset_tokens force row level security;

revoke all privileges on table public.izzy_password_reset_tokens from anon, authenticated;

commit;
