create table if not exists public.izzy_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  fecha text,
  agente text not null,
  cliente_nombre text not null,
  cliente_apellido text not null default '',
  telefono_primario text,
  telefono_secundario text,
  email text,
  fecha_nacimiento text,
  direccion text,
  apartamento text,
  ciudad text,
  estado text,
  zip text,
  proveedor_servicio text,
  proveedor_otro text,
  velocidad_deseada text,
  voice_service boolean not null default false,
  notas_instalacion text,
  autopay boolean not null default false,
  monthly_price numeric,
  special_notes text,
  order_number text,
  btn text,
  order_date text,
  install_date date,
  card_last4 text,
  signature_data text,
  payload jsonb not null default '{}'::jsonb
);

alter table public.izzy_orders enable row level security;
alter table public.izzy_orders force row level security;

revoke all privileges on table public.izzy_orders from anon, authenticated;
