begin;

create table if not exists public.izzy_rank_levels (
  code text primary key,
  name text not null,
  sort_order integer not null,
  is_career boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_rank_levels_code_check check (code in ('novato', 'agente', 'supervisor', 'director', 'embajador'))
);

create table if not exists public.izzy_service_categories (
  code text primary key,
  name text not null,
  sort_order integer not null,
  active boolean not null default true,
  visible_examples jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_service_categories_code_check check (code in ('basic', 'standard', 'premium'))
);

create table if not exists public.izzy_commission_rates (
  id bigint generated by default as identity primary key,
  rank_code text not null references public.izzy_rank_levels(code) on delete cascade,
  service_category_code text not null references public.izzy_service_categories(code) on delete cascade,
  sale_type text not null,
  amount numeric(12,2) not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_commission_rates_sale_type_check check (sale_type in ('residential', 'commercial')),
  constraint izzy_commission_rates_unique unique (rank_code, service_category_code, sale_type)
);

create table if not exists public.izzy_director_bonus_rates (
  id bigint generated by default as identity primary key,
  service_category_code text not null references public.izzy_service_categories(code) on delete cascade,
  sale_type text not null,
  amount numeric(12,2) not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_director_bonus_rates_sale_type_check check (sale_type in ('residential', 'commercial')),
  constraint izzy_director_bonus_rates_unique unique (service_category_code, sale_type)
);

create table if not exists public.izzy_activity_rules (
  rank_code text primary key references public.izzy_rank_levels(code) on delete cascade,
  min_personal_installs_month integer not null default 0,
  min_active_agents integer not null default 0,
  min_active_supervisors integer not null default 0,
  min_org_installs_month integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.izzy_rank_requirements (
  from_rank_code text primary key references public.izzy_rank_levels(code) on delete cascade,
  to_rank_code text not null references public.izzy_rank_levels(code) on delete cascade,
  min_lifetime_personal_installs integer not null default 0,
  min_active_agents integer not null default 0,
  min_active_supervisors integer not null default 0,
  min_org_installs_month integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.izzy_compensation_settings (
  key text primary key,
  value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

create table if not exists public.izzy_agent_rank_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.izzy_portal_users(id) on delete cascade,
  previous_rank_code text references public.izzy_rank_levels(code),
  new_rank_code text not null references public.izzy_rank_levels(code),
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  effective_at timestamptz not null default now()
);

create table if not exists public.izzy_compensation_audit_log (
  id bigint generated by default as identity primary key,
  actor_name text,
  actor_role text,
  entity_type text not null,
  entity_key text not null,
  action text not null,
  before_value jsonb,
  after_value jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.izzy_ambassadors (
  id bigint generated by default as identity primary key,
  code text not null unique,
  nombre text not null,
  telefono text,
  email text,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.izzy_commission_reserves (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.izzy_orders(id) on delete cascade,
  carrier_name text,
  reserve_days integer not null default 120,
  status text not null default 'reserve',
  reserve_started_at timestamptz not null default now(),
  release_at timestamptz,
  released_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_commission_reserves_status_check check (status in ('reserve', 'released', 'chargeback'))
);

alter table public.izzy_portal_users
  add column if not exists compensation_role text not null default 'novato',
  add column if not exists sponsor_user_id bigint references public.izzy_portal_users(id) on delete set null,
  add column if not exists manager_user_id bigint references public.izzy_portal_users(id) on delete set null;

alter table public.izzy_portal_users
  drop constraint if exists izzy_portal_users_compensation_role_check;

alter table public.izzy_portal_users
  add constraint izzy_portal_users_compensation_role_check
  check (compensation_role in ('novato', 'agente', 'supervisor', 'director', 'embajador'));

create index if not exists izzy_portal_users_comp_role_idx
  on public.izzy_portal_users (compensation_role);

create index if not exists izzy_portal_users_manager_idx
  on public.izzy_portal_users (manager_user_id);

alter table public.izzy_orders
  add column if not exists portal_user_id bigint references public.izzy_portal_users(id) on delete set null,
  add column if not exists sale_type text not null default 'residential',
  add column if not exists service_category_code text references public.izzy_service_categories(code) on delete set null,
  add column if not exists carrier_name text,
  add column if not exists compensation_status text not null default 'estimated',
  add column if not exists compensation_rank_code text references public.izzy_rank_levels(code) on delete set null,
  add column if not exists compensation_estimated_amount numeric(12,2),
  add column if not exists compensation_approved_at timestamptz,
  add column if not exists reserve_release_at timestamptz,
  add column if not exists chargeback_at timestamptz,
  add column if not exists chargeback_notes text,
  add column if not exists ambassador_id bigint references public.izzy_ambassadors(id) on delete set null;

alter table public.izzy_orders
  drop constraint if exists izzy_orders_sale_type_check;

alter table public.izzy_orders
  add constraint izzy_orders_sale_type_check
  check (sale_type in ('residential', 'commercial'));

alter table public.izzy_orders
  drop constraint if exists izzy_orders_compensation_status_check;

alter table public.izzy_orders
  add constraint izzy_orders_compensation_status_check
  check (compensation_status in ('estimated', 'approved', 'reserve', 'released', 'paid', 'chargeback'));

create index if not exists izzy_orders_portal_user_id_idx
  on public.izzy_orders (portal_user_id);

create index if not exists izzy_orders_compensation_status_idx
  on public.izzy_orders (compensation_status);

create index if not exists izzy_orders_actual_install_date_idx
  on public.izzy_orders (actual_install_date);

update public.izzy_orders o
set
  portal_user_id = u.id,
  carrier_name = coalesce(nullif(o.carrier_name, ''), nullif(o.proveedor_servicio, '')),
  compensation_rank_code = coalesce(o.compensation_rank_code, u.compensation_role)
from public.izzy_portal_users u
where u.nombre = o.agente
  and (
    o.portal_user_id is null
    or o.carrier_name is null
    or o.compensation_rank_code is null
  );

update public.izzy_orders
set service_category_code = case
  when coalesce(velocidad_deseada, '') ilike '%2 gig%' then 'premium'
  when coalesce(velocidad_deseada, '') ilike '%1 gig%' then 'premium'
  when coalesce(velocidad_deseada, '') ilike '%fiber%' then 'premium'
  when coalesce(velocidad_deseada, '') ilike '%500%' then 'standard'
  when coalesce(velocidad_deseada, '') ilike '%300%' then 'standard'
  when coalesce(velocidad_deseada, '') ilike '%promo%' then 'basic'
  when coalesce(velocidad_deseada, '') ilike '%special%' then 'basic'
  else coalesce(service_category_code, 'standard')
end
where service_category_code is null;

update public.izzy_orders
set compensation_status = case
  when commission_status = 'paid' then 'paid'
  when commission_status = 'earned' then 'reserve'
  when commission_status = 'cancelled' then 'chargeback'
  else 'estimated'
end
where compensation_status is null
   or compensation_status = 'estimated';

insert into public.izzy_rank_levels (code, name, sort_order, is_career, active)
values
  ('novato', 'Novato', 1, true, true),
  ('agente', 'Agente', 2, true, true),
  ('supervisor', 'Supervisor', 3, true, true),
  ('director', 'Director', 4, true, true),
  ('embajador', 'Programa de Embajadores', 99, false, true)
on conflict (code) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_career = excluded.is_career,
  active = excluded.active,
  updated_at = now();

insert into public.izzy_service_categories (code, name, sort_order, visible_examples, active)
values
  ('basic', 'Basico', 1, '["Servicios promocionales", "Programas especiales"]'::jsonb, true),
  ('standard', 'Estandar', 2, '["Internet residencial", "Spectrum 300", "Spectrum 500", "Frontier 500", "T-Mobile Home Internet"]'::jsonb, true),
  ('premium', 'Premium', 3, '["Spectrum 1 Gig", "Spectrum 2 Gig", "AT&T Fiber", "Frontier 1 Gig", "Servicios de mayor valor"]'::jsonb, true)
on conflict (code) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  visible_examples = excluded.visible_examples,
  active = excluded.active,
  updated_at = now();

insert into public.izzy_commission_rates (rank_code, service_category_code, sale_type, amount)
values
  ('novato', 'basic', 'residential', 25),
  ('novato', 'standard', 'residential', 40),
  ('novato', 'premium', 'residential', 50),
  ('agente', 'basic', 'residential', 40),
  ('agente', 'standard', 'residential', 75),
  ('agente', 'premium', 'residential', 100),
  ('supervisor', 'basic', 'residential', 50),
  ('supervisor', 'standard', 'residential', 90),
  ('supervisor', 'premium', 'residential', 150),
  ('director', 'basic', 'residential', 50),
  ('director', 'standard', 'residential', 90),
  ('director', 'premium', 'residential', 150),
  ('novato', 'basic', 'commercial', 75),
  ('novato', 'standard', 'commercial', 120),
  ('novato', 'premium', 'commercial', 150),
  ('agente', 'basic', 'commercial', 120),
  ('agente', 'standard', 'commercial', 225),
  ('agente', 'premium', 'commercial', 300),
  ('supervisor', 'basic', 'commercial', 150),
  ('supervisor', 'standard', 'commercial', 270),
  ('supervisor', 'premium', 'commercial', 450),
  ('director', 'basic', 'commercial', 150),
  ('director', 'standard', 'commercial', 270),
  ('director', 'premium', 'commercial', 450)
on conflict (rank_code, service_category_code, sale_type) do update
set
  amount = excluded.amount,
  active = true,
  updated_at = now();

insert into public.izzy_director_bonus_rates (service_category_code, sale_type, amount)
values
  ('basic', 'residential', 2),
  ('standard', 'residential', 5),
  ('premium', 'residential', 20),
  ('basic', 'commercial', 6),
  ('standard', 'commercial', 15),
  ('premium', 'commercial', 60)
on conflict (service_category_code, sale_type) do update
set
  amount = excluded.amount,
  active = true,
  updated_at = now();

insert into public.izzy_activity_rules (
  rank_code,
  min_personal_installs_month,
  min_active_agents,
  min_active_supervisors,
  min_org_installs_month
)
values
  ('novato', 3, 0, 0, 0),
  ('agente', 5, 0, 0, 0),
  ('supervisor', 5, 5, 0, 0),
  ('director', 5, 0, 1, 0),
  ('embajador', 0, 0, 0, 0)
on conflict (rank_code) do update
set
  min_personal_installs_month = excluded.min_personal_installs_month,
  min_active_agents = excluded.min_active_agents,
  min_active_supervisors = excluded.min_active_supervisors,
  min_org_installs_month = excluded.min_org_installs_month,
  active = true,
  updated_at = now();

insert into public.izzy_rank_requirements (
  from_rank_code,
  to_rank_code,
  min_lifetime_personal_installs,
  min_active_agents,
  min_active_supervisors,
  min_org_installs_month
)
values
  ('novato', 'agente', 10, 0, 0, 0),
  ('agente', 'supervisor', 20, 5, 0, 0),
  ('supervisor', 'director', 0, 0, 1, 25)
on conflict (from_rank_code) do update
set
  to_rank_code = excluded.to_rank_code,
  min_lifetime_personal_installs = excluded.min_lifetime_personal_installs,
  min_active_agents = excluded.min_active_agents,
  min_active_supervisors = excluded.min_active_supervisors,
  min_org_installs_month = excluded.min_org_installs_month,
  active = true,
  updated_at = now();

insert into public.izzy_compensation_settings (key, value, description)
values
  ('commercial_multiplier', '{"value": 3}'::jsonb, 'Multiplicador base para negocios/comercial.'),
  ('producer_elite_threshold', '{"monthly_installs": 10}'::jsonb, 'Instalaciones personales requeridas para Productor Elite.'),
  ('ambassador_program', '{"payout_per_install": 15, "active_window_days": 90, "minimum_installs_to_stay_active": 1}'::jsonb, 'Configuracion independiente del Programa de Embajadores IZZY.'),
  ('default_chargeback_days', '{"days": 120}'::jsonb, 'Reserva anti-chargeback por defecto.'),
  ('carrier_policies', '{"default": {"chargeback_days": 120}, "Spectrum": {"chargeback_days": 120}, "Frontier": {"chargeback_days": 120}, "AT&T Fiber": {"chargeback_days": 120}, "T-Mobile Home Internet": {"chargeback_days": 120}}'::jsonb, 'Politicas configurables por carrier para reserva/anti-chargeback.'),
  ('compensation_payout_frequency', '{"value": "monthly"}'::jsonb, 'Frecuencia de pago de comisiones.')
on conflict (key) do update
set
  value = excluded.value,
  description = excluded.description,
  updated_at = now();

insert into public.izzy_ambassadors (code, nombre, active)
values
  ('EMB-001', 'Embajador Demo', false)
on conflict (code) do nothing;

commit;
