begin;

alter table public.izzy_portal_users
  add column if not exists email text;

create unique index if not exists izzy_portal_users_email_idx
  on public.izzy_portal_users (lower(email))
  where email is not null;

create table if not exists public.izzy_password_reset_requests (
  id bigint generated by default as identity primary key,
  user_id bigint references public.izzy_portal_users(id) on delete set null,
  pin_code text,
  email text,
  status text not null default 'pending' check (status in ('pending', 'resolved')),
  requested_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.izzy_password_reset_requests enable row level security;
alter table public.izzy_password_reset_requests force row level security;

revoke all privileges on table public.izzy_password_reset_requests from anon, authenticated;

commit;
