begin;

alter table public.izzy_compensation_audit_log
  add column if not exists reason text;

create table if not exists public.izzy_carriers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  service_type text not null default 'internet',
  active boolean not null default true,
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_carriers_service_type_check
    check (service_type in ('internet', 'wireless', 'fiber', 'satellite', 'reseller', 'other'))
);

create table if not exists public.izzy_compensation_plans (
  id bigint generated by default as identity primary key,
  carrier_id bigint not null references public.izzy_carriers(id) on delete cascade,
  plan_name text not null,
  service_category_code text not null references public.izzy_service_categories(code) on delete restrict,
  sale_type text not null,
  novice_commission numeric(12,2) not null default 0,
  agent_commission numeric(12,2) not null default 0,
  supervisor_commission numeric(12,2) not null default 0,
  director_commission numeric(12,2) not null default 0,
  director_bonus numeric(12,2) not null default 0,
  commercial_multiplier numeric(12,2) not null default 1,
  chargeback_days integer not null default 120,
  special_bonuses jsonb not null default '[]'::jsonb,
  temporary_promo_notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_compensation_plans_sale_type_check
    check (sale_type in ('residential', 'commercial')),
  constraint izzy_compensation_plans_unique unique (carrier_id, plan_name, sale_type)
);

create table if not exists public.izzy_compensation_promotions (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date,
  rules jsonb not null default '{}'::jsonb,
  amount numeric(12,2) not null default 0,
  active boolean not null default true,
  promotion_type text not null default 'special_bonus',
  carrier_id bigint references public.izzy_carriers(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint izzy_compensation_promotions_type_check
    check (promotion_type in ('install_bonus', 'commercial_bonus', 'campaign_bonus', 'carrier_bonus', 'elite_bonus', 'special_bonus'))
);

create index if not exists izzy_compensation_plans_carrier_idx
  on public.izzy_compensation_plans (carrier_id, active);

create index if not exists izzy_compensation_promotions_active_idx
  on public.izzy_compensation_promotions (active, start_date, end_date);

drop trigger if exists set_izzy_carriers_updated_at on public.izzy_carriers;
create trigger set_izzy_carriers_updated_at
before update on public.izzy_carriers
for each row execute function public.set_updated_at();

drop trigger if exists set_izzy_compensation_plans_updated_at on public.izzy_compensation_plans;
create trigger set_izzy_compensation_plans_updated_at
before update on public.izzy_compensation_plans
for each row execute function public.set_updated_at();

drop trigger if exists set_izzy_compensation_promotions_updated_at on public.izzy_compensation_promotions;
create trigger set_izzy_compensation_promotions_updated_at
before update on public.izzy_compensation_promotions
for each row execute function public.set_updated_at();

insert into public.izzy_carriers (name, service_type, active, internal_notes)
values
  ('Spectrum', 'internet', true, 'Carrier inicial'),
  ('Frontier', 'fiber', true, 'Carrier inicial'),
  ('AT&T', 'fiber', true, 'Carrier inicial'),
  ('T-Mobile', 'wireless', true, 'Carrier inicial'),
  ('Starlink', 'satellite', true, 'Carrier inicial'),
  ('Revendedores', 'reseller', true, 'Canal reseller'),
  ('Otros futuros', 'other', true, 'Placeholder para expansion futura')
on conflict (name) do update
set
  service_type = excluded.service_type,
  active = excluded.active,
  internal_notes = excluded.internal_notes,
  updated_at = now();

with carrier_map as (
  select id, name from public.izzy_carriers
)
insert into public.izzy_compensation_plans (
  carrier_id,
  plan_name,
  service_category_code,
  sale_type,
  novice_commission,
  agent_commission,
  supervisor_commission,
  director_commission,
  director_bonus,
  commercial_multiplier,
  chargeback_days,
  active
)
values
  ((select id from carrier_map where name = 'Spectrum'), 'Spectrum 300', 'standard', 'residential', 40, 75, 90, 90, 5, 3, 120, true),
  ((select id from carrier_map where name = 'Spectrum'), 'Spectrum 1 Gig', 'premium', 'residential', 50, 100, 150, 150, 20, 3, 120, true),
  ((select id from carrier_map where name = 'Frontier'), 'Frontier 500', 'standard', 'residential', 40, 75, 90, 90, 5, 3, 120, true),
  ((select id from carrier_map where name = 'AT&T'), 'AT&T Fiber', 'premium', 'residential', 50, 100, 150, 150, 20, 3, 120, true),
  ((select id from carrier_map where name = 'T-Mobile'), 'T-Mobile Home Internet', 'standard', 'residential', 40, 75, 90, 90, 5, 3, 120, true)
on conflict (carrier_id, plan_name, sale_type) do update
set
  service_category_code = excluded.service_category_code,
  novice_commission = excluded.novice_commission,
  agent_commission = excluded.agent_commission,
  supervisor_commission = excluded.supervisor_commission,
  director_commission = excluded.director_commission,
  director_bonus = excluded.director_bonus,
  commercial_multiplier = excluded.commercial_multiplier,
  chargeback_days = excluded.chargeback_days,
  active = excluded.active,
  updated_at = now();

insert into public.izzy_compensation_promotions (
  name,
  start_date,
  end_date,
  rules,
  amount,
  active,
  promotion_type,
  notes
)
values
  ('Productor Elite Base', current_date, null, '{"monthly_installs": 10}'::jsonb, 0, true, 'elite_bonus', 'Reconocimiento base configurable'),
  ('Bono comercial base', current_date, null, '{"sale_type": "commercial"}'::jsonb, 0, false, 'commercial_bonus', 'Placeholder editable desde admin')
on conflict do nothing;

commit;
